config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get 'pages/development'

  get 'pages/phones'

  get 'pages/reddit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def development
  end

  def phones
  end

  def reddit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tech</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/pages/development.html.erb
<div class="container"> 
  <div class="card large">
    <div class="card-image">
      <img src="http://materializecss.com/images/sample-1.jpg">
      <span class="card-title">Development</span>
    </div>
    <div class="card-content">
      <p>Web Development is hard as hell. The key is practice.</p>
      <p>Enjoy some place holder text. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <h1>Welcome</h1>
  <div class="card large">
    <div class="slider">
      <ul class="slides">
        <li>
          <img src="http://www.vactualpapers.com/web/wallpapers/material-design-hd-wallpaper-no-0728/thumbnail/lg.png" alt="">
          <div class="caption left-align">
            <h3>Material Design</h3>
            <h5 class="light grey-text text-lighten-3"></h5>
          </div>
        </li>
        <li>
          <img src="http://www.img.lirent.net/2014/10/Android-Lollipop-wallpapers-m.png" alt="">
          <div class="caption right-align">
            <h3></h3>
            <h5 class="light grey-text text-lighten-3">So Clean</h5>
          </div>
        </li>
        <li>
          <img src="http://awesomwallpaper.com/img2/A181FE3959C08E3D/material-design.jpg" alt="">
          <div class="caption center-align">
            <h3>Much Wow</h3>
            <h5 class="light grey-text text-lighten-3"></h5>
          </div>
        </li>
      </ul>
      <div class="card-content home-card">
        <p>Andrew told our class to create an app that showcases our interests/hobbies. I'm a geek who reddits all day and likes technology. I especially like cell phones.</p>
      </div>
    </div>
  </div>

  <script>
  $(document).ready(function(){
    // Init Carousel
    $('.carousel').carousel();

    // Init Carousel Slider
    $('.carousel.carousel-slider').carousel({fullWidth:true});

    // Fire off toast
    //Materialize.toast('Hello World', 3000);

    // Init Slider
    $('.slider').slider();

    // Init Modal
    $('.modal').modal();

    // Init Sidenav
    $('.button-collapse').sideNav();
  });
  </script>
</div>

app/views/pages/phones.html.erb
<div class="container">  
 <h2 class="header">Phones</h2>
 <div class="card horizontal">
   <div class="card-image">
     <img src="https://www.androidcentral.com/sites/androidcentral.com/files/styles/larger_wm_brw/public/article_images/2016/10/pixel-xl-black-on-wood.jpg?itok=gMpPQOFW">
   </div>
   <div class="card-stacked">
     <div class="card-content">
      <p>#TeamPixel</p>
      <p>At least for now, that new iPhone is looking pretty appealing</p>
     </div>
      <div class="card-action">
       <a href="https://madeby.google.com/phone/" target="_blank">Learn more the the Google Pixel</a>
     </div>
   </div>
 </div>

 <div class="card horizontal">
   <div class="card-image">
     <img src="https://cnet2.cbsistatic.com/img/rqWPNhxfi5aISDF-aBuk_7q2yco=/fit-in/570x0/2017/09/15/2b3da9d0-d284-457b-acdd-177de159db5e/apple-091217-iphone-x-3986-1.jpg">
   </div>
   <div class="card-stacked">
     <div class="card-content">
      <p>Update: Leaks for the new pixel suck. Am planning on switching back to iOS</p>
     </div>
     <div class="card-action">
       <a href="https://www.apple.com/iphone-x/" target="_blank">Learn more about the iPhone X</a>
     </div>
   </div>
 </div>
</div>

  

app/views/pages/reddit.html.erb
<div class="container">
  <h1>Reddit</h1>
 <div class="card blue-grey darken-1">
   <div class="card-content white-text">
     <span class="card-title"></span>
     <p>Check out this video if you are not familar with Reddit</p><br>
     <div class="video-container">
       <iframe width="560" height="315" src="https://www.youtube.com/embed/tlI022aUWQQ?rel=0" frameborder="0" allowfullscreen></iframe>
     </div>
   </div>
   <div class="card-action">
     <a href="https://www.reddit.com/" target="_blank">Link to Reddit!</a>
   </div>
 </div>
</div>

app/views/shared/_nav.html.erb
<nav>
  <div class="nav-wrapper light-blue darken-2">
    <a href="" class="brand-logo">Logo</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to link_to "Home", root_path %></li>
      <li><%= link_to link_to "Development", pages_development_path %></li>
      <li><%= link_to link_to "Phones", pages_phones_path %></li>
      <li><%= link_to link_to "Reddit", pages_reddit_path %></li>
    </ul>
  </div>
</nav>